# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgwRSv6SNZnLWSshBLHHjarDxCDwPadO
"""

import setuptools

REQUIRED_PACKAGES = ['google-cloud-storage==1.33.0']
PACKAGE_NAME = 'mypackage'
PACKAGE_VERSION = '0.0.1'

setuptools.setup(
    name=PACKAGE_NAME,
    version=PACKAGE_VERSION,
    author='Shashwat Sagar',
    author_email='shashwat.sagar@protonmail.com',
    url='https://www.python.org/sigs/distutils-sig/',
    description='Demo POV',
    install_requires=REQUIRED_PACKAGES,
    packages=['mypackage'],
)